# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: 'Default'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '02c671a8-8d74-4af7-b072-882e8643b21e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'skillup-9cc93d7e-rg'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/artemvashchenkonix/ARMPipeline-repo/refs/heads/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName Test'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'